[package]
name = "rmemimg"
version = "0.1.0"
edition = "2021"

[lib]
name = "rmemimg"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
rust_decimal = "1.36"

[dev-dependencies]
